### Project ###
### " Egyptian Grocery Analysis Using Association Rules " ###

In [ ]:
!pip install apyori

In [ ]:
!pip install mlxtend

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from apyori import apriori

In [33]:
data = pd.read_excel('Egyptian_Grocery_Transactions.xlsx', header = None)

In [35]:
data.head()

                   0
0        سكر,لبن,شاي
1         فراخ,بطاطس
2            رز,فراخ
3  عسل,لحمة,رز,زبادي
4         بصل,رز,عدس

In [37]:
len(data)

20

In [39]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [41]:
data.columns = ['Items']
data

                                 Items
0                          سكر,لبن,شاي
1                           فراخ,بطاطس
2                              رز,فراخ
3                    عسل,لحمة,رز,زبادي
4                           بصل,رز,عدس
5                شيبسي,فلفل,بيبسي,مياه
6                     فراخ,بطاطس,شيبسي
7                 طماطم,عدس,كورن فليكس
8                عسل,مربة,زيت,عيش بلدي
9        فراخ,مكرونة,شاي,كشري,سكر,سمنة
10                             عسل,عدس
11   زيت,بيض,فول,مكرونة,صلصة,جبنة قريش
12           شاي,عدس,عسل,زيت,بيبسي,بيض
13                         رز,عدس,كشري
14                       كشري,عيش بلدي
15                      لبن,بيبسي,مربة
16                 سكر,عيش بلدي,مكرونة
17                   بيبسي,زبادي,طعمية
18           بيبسي,سكر,زيت,عدس,فول,بيض
19  بيض,بيبسي,طعمية,سكر,سمنة,جبنة قريش

In [ ]:
items = data['Items'].values
items

In [ ]:
transactions = []
for i in range(0, len(items)):
    transactions.append(items[i].split(","))

transactions

In [ ]:
encoder = TransactionEncoder()
encoded_data = encoder.fit_transform(transactions)

encoded_data

In [ ]:
encodedData = pd.DataFrame(encoded_data, columns = encoder.columns_, dtype = int)
encodedData.head()

In [ ]:
support = apriori (encodedData, min_support = 0.1, use_colnames = True)
support.sort_values(by = 'support', ascending = False)

In [ ]:
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
confidence = association_rules(support, metric = 'confidence', min_threshold = 0.3)
confidence.sort_values(by = 'confidence', ascending = False)

In [ ]:
# Strongest Associations:
    The top rules show perfect confidence (100%):
    (سكر, بيبسي) → (بيض): When customers buy sugar and Pepsi together, they always buy eggs
    (عدس, بيبسي, بيض) → (زيت): Lentils, Pepsi and eggs always lead to oil purchase
    (بطاطس) → (فراخ): Potato purchases always lead to chicken purchases

# High-Impact Items:
    Pepsi (بيبسي) appears in most of the strongest rules
    Eggs (بيض) are frequently purchased with other items
    Oil (زيت) appears as a common consequent in high-confidence rules

# Lift Values:
    The highest lift (5.0) shows these combinations occur 5x more than random chance:
    (سكر, بيبسي) → (بيض)
    (عدس, بيبسي, بيض) → (زيت)
    (بطاطس) → (فراخ)
    
# Weak Assocciation
    Rules at the bottom show 33% confidence (1 in 3 occurrences):
    Lentils (عدس) lead to honey (عسل) 33% of the time
    Pepsi leads to eggs+oil combo 33% of the time